import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { validateRequest } from "@/auth";
import { redirect } from "next/navigation";
import ReactQueryProvider from "../reactQueryProvider";
import SessionProvider from "../sessionProvider";
import Link from "next/link";
import { logout } from "../(auth)/logout/action";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await validateRequest();

  if (!session.user) redirect("/login");

  return (
    <html lang="en">
      <body className={fontSans.variable}>
        <ReactQueryProvider>
          <SessionProvider value={session}>
            <div className="flex h-screen">
              <aside className="w-32 bg-base-100 p-4 shadow-lg">
                <div className="py-4 text-center text-xl font-bold">CMS</div>
                <nav className="space-y-2">
                  <Link
                    prefetch={false}
                    href="/contents"
                    className={`btn btn-outline btn-primary btn-block`}
                  >
                    Content
                  </Link>
                  <Link
                    prefetch={false}
                    href="/users"
                    className={`btn btn-outline btn-primary btn-block`}
                  >
                    Users
                  </Link>
                  <Link
                    prefetch={false}
                    href="/categories"
                    className={`btn btn-outline btn-primary btn-block`}
                  >
                    Categories
                  </Link>
                  <Link
                    prefetch={false}
                    href="/products"
                    className={`btn btn-outline btn-primary btn-block`}
                  >
                    Products
                  </Link>
                  <Link
                    prefetch={false}
                    href="/orders"
                    className={`btn btn-outline btn-primary btn-block`}
                  >
                    Orders
                  </Link>

                  <div
                  onClick={logout}
                    className={`btn btn-outline btn-primary btn-block`}
                  >
                    Logout
                  </div>
                </nav>
              </aside>
              <main className="flex-1 p-4">{children}</main>
            </div>
          </SessionProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
